name: Deploy to BigQuery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set Project
        run: gcloud config set project costco-project-488314

      # ---- Deploy Silver ----
      - name: Deploy Silver Layer
        run: |
          bq query --use_legacy_sql=false < sql/silver/sales_cleaned.sql

      # ---- Data Quality Test ----
      - name: Check for Null Sales
        run: |
          NULL_COUNT=$(bq query --use_legacy_sql=false --format=csv \
          "SELECT COUNT(*) FROM costco_silver.sales_cleaned WHERE Sales IS NULL" | tail -n 1)

          echo "Null Count: $NULL_COUNT"

          if [ "$NULL_COUNT" -gt 0 ]; then
            echo "Data Quality Check Failed!"
            exit 1
          fi

      # ---- Deploy Gold ----
      - name: Deploy Gold Layer
        run: |
          bq query --use_legacy_sql=false < sql/gold/sales_summary.sql

