name: Deploy to BigQuery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set Project
        run: gcloud config set project costco-project-488314

      - name: Deploy Silver Layer
        run: |
          bq query --use_legacy_sql=false < sql/silver/sales_cleaned.sql

